kind: pipeline
name: docker-deployment
type: docker

steps:
  - name: deploy
    image: cyberia_ci_worker
    pull: never
    environment:
      SSH_KEY:
        from_secret: SSH_KEY
    commands:
    - eval `ssh-agent`
    - echo "$SSH_KEY" | ssh-add -
    - ssh dockerci@cyberia -- '-f /wired/wired_enc/jakub/cebula.py/docker-compose.yml restart'
    - kill "$SSH_AGENT_PID"

